/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu_principal;

import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin
 */
public class selec_carpeta extends javax.swing.JInternalFrame {

    /**
     * Creates new form selec_carpeta
     */
    public selec_carpeta() {
        initComponents();
        this.respaldo.setAcceptAllFileFilterUsed(false);
        JFileChooser fileChooser = new JFileChooser();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        respaldo = new javax.swing.JFileChooser();

        setClosable(true);
        setTitle("CARPETA DE DESTINO - RESPALDO BD");

        respaldo.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        respaldo.setDialogTitle("");
        respaldo.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        respaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respaldoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(respaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(respaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void respaldar(String f, String d){
        try {
           //d=d.replace("\\", "\\\\");
      Process p = Runtime
            .getRuntime()
            .exec("C:\\xampp\\mysql\\bin\\mysqldump --host sql5.freemysqlhosting.net -P 3306 -u sql5113770 -pRXv6DPXMwF sql5113770");

      InputStream is = p.getInputStream();
      FileOutputStream fos = new FileOutputStream(d+"\\backup-"+f+".sql");
      byte[] buffer = new byte[1000];

      int leido = is.read(buffer);
      while (leido > 0) {
         fos.write(buffer, 0, leido);
         leido = is.read(buffer);
      }

      fos.close();

   } catch (Exception e) {
      e.printStackTrace();
   }
    }
    private void respaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respaldoActionPerformed
        // TODO add your handling code here:
        if (JFileChooser.APPROVE_SELECTION.equals(evt.getActionCommand())) {
          File url = this.respaldo.getSelectedFile();
          String direccion = url.toString();
          if(!direccion.equals("")){
             Date date = (Date) Calendar.getInstance().getTime();
            SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
            String fecha = formatter.format(date);
            JOptionPane.showMessageDialog(null, fecha);
            this.respaldar(fecha, direccion);
            this.dispose();
            JOptionPane.showMessageDialog(null, "Respaldo realizado con éxito!");
          }
        } else if (JFileChooser.CANCEL_SELECTION.equals(evt.getActionCommand())) {
            this.dispose();
        }

    }//GEN-LAST:event_respaldoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser respaldo;
    // End of variables declaration//GEN-END:variables
}
